### ISSUE TITLE
Managing special characters for NLU automatic training

### ISSUE THREAD

**Issue by rtroncy** [marcotrinelli/FADE#1]
Problem: This [line of code](https://github.com/marcotrinelli/FADE/blob/3a1fa0f7895e86efc89ab48d43f98ab20533de00/src/FADE.py#L73) is supposed to post-process dictionaries of entities extracted from a knowledge graph for being used automatically in NLU training. You noticed that some characters were invalid and need to be replaced by an empty string.

ToDo
 - [x] list the set of reserved characters for DialogFlow and either escape them or replace them with a white space string
 - [x] list the set of reserved characters for Lex and either escape them or replace them with a white space string
 - [x] list the set of reserved characters for Wit and either escape them or replace them with a white space string

**Comment by ehrhart** [comment]
For Dialogflow, I couldn't find an official list of reserved characters, so I've tried with all of them, it turns out they don't allow the following characters:

```
" ( ) < > \ [ ] ^ _ | { }
```
[Control characters](https://en.wikipedia.org/wiki/Control_character) are also forbidden.

This can be translated into a Regular Expression:

```
/["\(\)<>\\\[\]^_\|{}\x00-\x09\x0B-\x0C\x0E-\x1F\x7F-\x9F]/g
```

In my opinion I would replace those characters with a space.

**Comment by marcotrinelli-zz** [comment]
Thank you for the help! I'll update the source code soon. Did you find a way to escape those characters?

**Comment by rtroncy** [comment]
Rather than escaping, the proposal is to replace them with a white space " " using the regex above. A similar inventory must be done with the 2 other NLUs

**Comment by ehrhart** [comment]
> Did you find a way to escape those characters?

I couldn't find a way to escape them, but replacing them with a space seems like a good compromise, especially since these characters don't really matter in the overall comprehension.

**Comment by marcotrinelli-zz** [comment]
I updated the source code, supporting now the replacement for Dialogflow

**Comment by marcotrinelli-zz** [comment]
Update: Wit.ai has no problem with special characters

**Comment by marcotrinelli-zz** [comment]
Update: Amazon Lex supports all the special characters too
